EXP_DIR: faster_rcnn_pvanet
TRAIN:
  USE_FLIPPED: False #True
  SNAPSHOT_ITERS: 5000
  BBOX_NORMALIZE_TARGETS: True
  ASPECT_GROUPING: False #True
  RPN_NMS_THRESH: 0.6
  HAS_RPN: True
  IMS_PER_BATCH: 1
  BBOX_NORMALIZE_TARGETS_PRECOMPUTED: True
  RPN_POSITIVE_OVERLAP: 0.7
  RPN_BATCHSIZE: 512 #256
  BATCH_SIZE: 256
  PROPOSAL_METHOD: gt
  BG_THRESH_LO: 0.0
  SCALE_MULTIPLE_OF: 32
  MAX_SIZE: 1000
  SCALES:
    - 416
    - 448
    - 480
    - 512
    - 544
    - 576
    - 608
    - 640
    - 672
    - 704
    - 736
    - 768
    - 800

